name: .NET

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  TOKENKEY: ${{ secrets.TOKENKEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./WebApp/WebApp2.sln
    - name: Build
      run: dotnet build --no-restore ./WebApp/WebApp2.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./WebApp/
